server:
  port: 9101
spring:
  application:
    name: DONGYIMAI-MANAGER
  #MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/dongyimai_db?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #开启数据库连接池监控
    filter: stat
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/offcn/manager/mapper/*.xml
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#日志
logging:
  file:
    path: E:\\logs\\dongyimai_manager
  level:
    com:
      offcn: debug
#Feign熔断
feign:
  hystrix:
    enabled: true #开启熔断